# Generated by Django 3.2 on 2021-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_auto_20210530_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
