# Generated by Django 3.2 on 2021-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0003_auto_20210530_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
